---
title: "Migration in the Americas: A Network Analysis Approach"
author: "Joey"
date: "`r Sys.Date()`"
output: 
  html_document:
    keep_md: TRUE
---

# Introduction
The following Repository reflects a project I initiated while completing a Network 
Analysis course for my Master's degree in International Policy and Development, 
with specialization in Data analysis. The Course was taught by the fabulous 
Dr. Phil Murphy and much credit must be given to him for this endeavor.

This Repository also reflects my early musings with more official/intentional 
organization of my data and related documentation with the goal of sharing it
with a larger professional and academic network. It is my goal to make this work
as readily and easily accessible to both those experienced in network analysis,
as well as for those who are more generally interested in the topic of migration,
and various methods for understanding and/or describing migration trends. 

I hope to build out this repository with accessible markdown files, which I will
hope to publish in another space (possibly RPubs) so that the relevant visualizations
of the various networks can be seen in tandem with text and code. This will be
a later but final goal. For now, I am in the data re-organization and GitHub 
orientation phase of this project. 

# Navigating this Repository
To understand this project, I have created README files for each subfolder branch point
that will hopefully help guide one in reviewing this project. To get a sense of the
Data-gathering and consolidation methods, navigate to the [MigrationData](https://github.com/jthebl/MigrationAmericas_NetworkAnalysis/tree/50146dfec499754fff72d8809971d308dfe1675b/Immigration_Networks/MigrationData) subfolder. To view the methods related to
constructing the network visualizations and related network analysis metrics, navigate
to the [ConstructingNetworks](https://github.com/jthebl/MigrationAmericas_NetworkAnalysis/tree/50146dfec499754fff72d8809971d308dfe1675b/Immigration_Networks/ConstructingNetworks) subfolder. To view a consolidated
folder of all the R-scripts used in this project, navigate to the [All_Rscripts](https://github.com/jthebl/MigrationAmericas_NetworkAnalysis/tree/50146dfec499754fff72d8809971d308dfe1675b/Immigration_Networks/All_Rscripts) subfolder. 
